cultuurnet/culturefeed

- culturefeed_entry_ui/includes/culturefeed_entry_ui.pages.inc
Yeah basicly wat the title says - because there was a needed bracket in the commented out code - the conditional was not closed properly.
> fix missing bracket error - comment was too greedy

- culturefeed_agenda/includes/blocks.inc
- culturefeed_agenda/lib/Drupal/AgendaSearchPage.php
- culturefeed_search_ui/includes/blocks.inc
- culturefeed_search_ui/includes/pages.inc
- culturefeed_search_ui/lib/Drupal/CultureFeedSearchPage.php
Reverts cultuurnet/culturefeed#94
> Revert "WKS-264: undo revert WKS-260 + add check on searching."

- culturefeed_agenda/theme/theme.inc
Fixed using wrong image variable (see #106).
> 106: Fixed using wrong variable.

- culturefeed_agenda/theme/culturefeed-event.tpl.php
> 112: Fixed notice when the UitPas module is not enabled.

- culturefeed_entry_ui/culturefeed_entry_ui.module
Added extra check if user is a Culturefeed user.
See #115
> 115: Fixed notice when checking a not culturefeed user.

- culturefeed_entry_ui/culturefeed_entry_ui.module
* Overwriting local tasks (tabs)
* Using the proper theme function
* Added active state checks.
See Issue #117.
> 117: Fixed overwriting local tasks (tabs), using proper theme function and added active state

- culturefeed_agenda/js/agenda_map.js
- culturefeed_agenda/js/map.js
> 124: Allow setting an alternative marker icon

- culturefeed_agenda/js/map.js
> 126: Allow altering the info window content

- culturefeed_agenda/lib/Drupal/AgendaSearchPage.php
> 130: Fixed notice CultureFeedAgendaPage->getActiveTrail()

- culturefeed_agenda/includes/helpers.inc
insert contact links into general links variable even if mediatype webresource or website exist
> UIV-1906 insert contact links into general links variable

- culturefeed.helpers.inc
Fixed issue #139 : Proper replacement pattern that support both http & https.
> 139: Fixed missing https support.

- culturefeed_agenda/theme/theme.inc
fix Notice: Undefined index: cdbid in _culturefeed_agenda_preprocess_event()
> UIV-1918 fix Notice: Undefined index: cdbid

- culturefeed_entry_ui/culturefeed_entry_ui.module
> 152 : Fixed fatal error when an event does no longer exists in the EntryAPI.

- culturefeed_search_views/views/plugins/culturefeed_search_views_query.inc
> Microtime returns string, should return float to be able to do numeric operations on it

- culturefeed_entry_ui/culturefeed_entry_ui.module
> Fix "Not a valid token set" exceptions flooding the logs

- culturefeed_agenda/includes/blocks.inc
- culturefeed_search_ui/culturefeed_search_ui.module
Reverts cultuurnet/culturefeed#176
> Revert "Feature/wks 332"

- culturefeed_agenda/theme/theme.inc
- culturefeed_search_ui/includes/pages.inc
- culturefeed_uitpas/includes/promotions.inc
UIV-2124 : De vraag was om een afbeelding in de rss feed te krijgen. Kan er iemand nakijken of dit op de juiste manier is gebeurd?
> Add image to rss feed

- culturefeed_search/culturefeed_search.module
- culturefeed_search/includes/admin.inc
- culturefeed_search/lib/Drupal/Import/CultureFeedCityImport.php
- culturefeed_search/lib/Drupal/Import/CultureFeedDomainImport.php
> feature/WKS-358: Make the Culturefeed search taxonomy endpoint configurable

- composer.lock
- culturefeed_agenda/theme/theme.inc
- culturefeed_search/includes/helpers.inc
- culturefeed_social/culturefeed_social.module
- culturefeed_social/includes/blocks.inc
- culturefeed_ui/culturefeed_ui.module
- culturefeed_uitpas/culturefeed_uitpas.helpers.inc
- culturefeed_uitpas/culturefeed_uitpas.module
- culturefeed_uitpas/culturefeed_uitpas.theme.inc
- culturefeed_uitpas/includes/event_details_advantages.inc
**main changes:**
- use new (faster) endpoint to get uitpas cardsystem prices
- increase cache expiration for uitpas data
- add caching for activity calls
- increase cache expiration for activity data
> refactor uitpas cardsystem calls & caching

- culturefeed_data_validation/culturefeed_data_validation.admin.inc
- culturefeed_data_validation/culturefeed_data_validation.helpers.inc
> feature/WKS-378: Make the datavalidation email verification grade configurable
